### ISSUE TITLE
Bug in AdamW optimizer

### ISSUE THREAD

**Issue by johnma2006** [joennlae/tensorli#1]
Hi,

There is a small implementation error in the AdamW optimizer here:
https://github.com/joennlae/tensorli/blob/f2ca7547f80f0ed66d373816eb2958806455eef2/tensorli/optimizerli.py#L48C17-L48C101
I believe should be `t.data -= self.lr * m_hat / (np.sqrt(v_hat) + self.eps) + self.lr * self.weight_decay * t.data`.

Best,
John

**Comment by joennlae** [comment]
Hi John 😄 

Thank you very much for the issue. You are absolutely right. I fixed this.

Have a good one, and cheers
Jannis

**Comment by johnma2006** [comment]
You're welcome 🤗
